version: '2'
services:
  app:
    build: .
    links:
      - rabbitmq
      - node
      - composer
    volumes:
      - .:/var/www/html
    ports:
      - 80:80

  node:
    image: node:6.2.2

  rabbitmq:
    image: cbergau/rabbitmqdelayedmsgs:3.6.2
    ports:
      - 15672:15672
      - 5672:5672

  composer:
    image: composer/composer:latest
